## Libs

In [110]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

In [111]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier, DistanceMetric
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, ConfusionMatrixDisplay

In [112]:
pd.options.display.max_columns = None

## Dataframe

### Read csv

#### Treino

In [119]:
train_df = pd.read_csv('https://raw.githubusercontent.com/AbnerNeves/Machine-Learning-Aplicado/master/Dados_Treino.csv')
train_df.head()

encounter_id  hospital_id   age        bmi  elective_surgery  ethnicity  \
0        214826          118  68.0  22.732803                 0  Caucasian   
1        246060           81  77.0  27.421875                 0  Caucasian   
2        276985          118  25.0  31.952749                 0  Caucasian   
3        262220          118  81.0  22.635548                 1  Caucasian   
4        201746           33  19.0        NaN                 0  Caucasian   

  gender  height hospital_admit_source           icu_admit_source  icu_id  \
0      M   180.3                 Floor                      Floor      92   
1      F   160.0                 Floor                      Floor      90   
2      F   172.7  Emergency Department       Accident & Emergency      93   
3      F   165.1        Operating Room  Operating Room / Recovery      92   
4      M   188.0                   NaN       Accident & Emergency      91   

  icu_stay_type      icu_type  pre_icu_los_days  readmission_status  weight  \
0         admit         CTICU          0.541667                   0    73.9   
1         admit  Med-Surg ICU          0.927778                   0    70.2   
2         admit  Med-Surg ICU          0.000694                   0    95.3   
3         admit         CTICU          0.000694                   0    61.7   
4         admit  Med-Surg ICU          0.073611                   0     NaN   

   albumin_apache  apache_2_diagnosis  apache_3j_diagnosis  \
0             2.3               113.0               502.01   
1             NaN               108.0               203.01   
2             NaN               122.0               703.03   
3             NaN               203.0              1206.03   
4             NaN               119.0               601.01   

   apache_post_operative  arf_apache  bilirubin_apache  bun_apache  \
0                      0           0               0.4        31.0   
1                      0           0               NaN         9.0   
2                      0           0               NaN         NaN   
3                      1           0               NaN         NaN   
4                      0           0               NaN         NaN   

   creatinine_apache  fio2_apache  gcs_eyes_apache  gcs_motor_apache  \
0               2.51          NaN              3.0               6.0   
1               0.56          1.0              1.0               3.0   
2                NaN          NaN              3.0               6.0   
3                NaN          0.6              4.0               6.0   
4                NaN          NaN              NaN               NaN   

   gcs_unable_apache  gcs_verbal_apache  glucose_apache  heart_rate_apache  \
0                0.0                4.0           168.0              118.0   
1                0.0                1.0           145.0              120.0   
2                0.0                5.0             NaN              102.0   
3                0.0                5.0           185.0              114.0   
4                NaN                NaN             NaN               60.0   

   hematocrit_apache  intubated_apache  map_apache  paco2_apache  \
0               27.4                 0        40.0           NaN   
1               36.9                 0        46.0          37.0   
2                NaN                 0        68.0           NaN   
3               25.9                 1        60.0          30.0   
4                NaN                 0       103.0           NaN   

   paco2_for_ph_apache  pao2_apache  ph_apache  resprate_apache  \
0                  NaN          NaN        NaN             36.0   
1                 37.0         51.0       7.45             33.0   
2                  NaN          NaN        NaN             37.0   
3                 30.0        142.0       7.39              4.0   
4                  NaN          NaN        NaN             16.0   

   sodium_apache  temp_apache  urineoutput_apache  ventilated_apache  \
0          134.0

In [120]:
train_df.shape

(117141, 180)

#### Teste

In [121]:
test_df = pd.read_csv('https://raw.githubusercontent.com/AbnerNeves/Machine-Learning-Aplicado/master/Dados_Teste.csv')
test_df.head()

encounter_id  hospital_id   age        bmi  elective_surgery  ethnicity  \
0        206833           19  37.0  27.109375                 0  Caucasian   
1        273200           86  47.0  28.071089                 1  Caucasian   
2        271053           79  74.0  21.661538                 0  Caucasian   
3        221599          120  18.0  17.617188                 0  Caucasian   
4        177808           86  80.0  29.880373                 0  Caucasian   

  gender  height hospital_admit_source           icu_admit_source  icu_id  \
0      F   160.0                 Floor                      Floor     653   
1      M   164.0        Operating Room  Operating Room / Recovery    1035   
2      F   162.5      Acute Care/Floor                      Floor     366   
3      F   160.0                   NaN       Accident & Emergency    1000   
4      F   162.6  Emergency Department       Accident & Emergency    1037   

  icu_stay_type      icu_type  pre_icu_los_days  readmission_status  weight  \
0         admit  Med-Surg ICU          4.277083                   0    69.4   
1         admit     CCU-CTICU          0.340278                   0    75.5   
2         admit  Med-Surg ICU          2.694444                   0    57.2   
3         admit     CCU-CTICU          0.102083                   0    45.1   
4         admit          SICU          0.114583                   0    79.0   

   albumin_apache  apache_2_diagnosis  apache_3j_diagnosis  \
0             NaN               109.0               108.01   
1             NaN               308.0              1207.01   
2             NaN               124.0               305.02   
3             NaN               120.0               407.01   
4             NaN               301.0               403.01   

   apache_post_operative  arf_apache  bilirubin_apache  bun_apache  \
0                      0           0               NaN        30.0   
1                      1           0               NaN        12.0   
2                      0           0               NaN        24.0   
3                      0           0               NaN         NaN   
4                      0           0               NaN         8.0   

   creatinine_apache  fio2_apache  gcs_eyes_apache  gcs_motor_apache  \
0               1.56          NaN              4.0               6.0   
1               0.65          0.8              4.0               4.0   
2               0.46          NaN              4.0               6.0   
3                NaN          NaN              4.0               6.0   
4               0.65          NaN              3.0               6.0   

   gcs_unable_apache  gcs_verbal_apache  glucose_apache  heart_rate_apache  \
0                0.0                5.0            84.0              118.0   
1                0.0                1.0           173.0               93.0   
2                0.0                5.0            61.0              102.0   
3                0.0                5.0             NaN              103.0   
4                0.0                4.0           106.0              131.0   

   hematocrit_apache  intubated_apache  map_apache  paco2_apache  \
0               23.3                 0       128.0           NaN   
1               28.6                 1        51.0          45.0   
2               18.5                 0        48.0           NaN   
3                NaN                 0        54.0           NaN   
4               28.7                 0        67.0           NaN   

   paco2_for_ph_apache  pao2_apache  ph_apache  resprate_apache  \
0                  NaN          NaN        NaN              6.0   
1                 45.0         95.0       7.29             28.0   
2                  NaN          NaN        NaN             14.0   
3                  NaN          NaN        NaN             12.0   
4                  NaN          NaN        NaN             28.0   

   sodium_apache  temp_apache  urineoutput_apache  ventilated_apache  \
0          134.0

### Columns

In [125]:
columns_todrop = ["hospital_id","hospital_admit_source","icu_admit_source","icu_id","icu_stay_type","icu_type",'pre_icu_los_days',\
                 'readmission_status']

In [123]:
train_df.drop(columns_todrop, inplace = True, axis=1)

In [124]:
test_df.drop(columns_todrop, inplace = True, axis=1)

### Tratamento de Dados

#### Dados binários

In [126]:
def ColumnToBinary(database,column_name,value_dict,nanfill,shoulddrop):
    new_df = database.copy()
    if (shoulddrop):
        new_df = new_df[new_df[column_name].notna()]
    else:
        new_df[column_name] = df[column_name].fillna(nanfill)
  
    new_df[column_name] = [value_dict[item] for item in new_df[column_name]]

    return new_df

##### Gênero

In [129]:
print("Train NaN No: ",train_df["gender"].isna().sum())

Train NaN No:  57


In [130]:
print("Test NaN No: ",test_df["gender"].isna().sum())

Test NaN No:  9


In [132]:
df_gender = {"M": 0, "F": 1}

In [135]:
train_df = ColumnToBinary(train_df,"gender",df_gender,"M",True)

In [136]:
train_df.gender.value_counts()

0    63471
1    53613
Name: gender, dtype: int64

#### ethnicity

In [137]:
col = "ethnicity"
train_df[col].unique()

array(['Caucasian', nan, 'Hispanic', 'African American', 'Asian',
       'Native American', 'Other/Unknown'], dtype=object)

In [31]:
print(" NaN No: ",df[col].isna().sum())

 NaN No:  1377


In [32]:
train_df_ethnicity = {"Caucasian": 0, "Hispanic": 1,"African American":2,
                      "Asian":3,"Native American":4,"Other/Unknown":5}

In [33]:
df = ColumnToBinary(df,col,train_df_ethnicity,"Other/Unknown",False)

In [34]:
df.tail(3)

encounter_id   age        bmi  elective_surgery  ethnicity  gender  \
117138        219719  73.0  32.265371                 0          2       0   
117139        222562  81.0  24.408579                 0          0       0   
117140        157942  35.0  30.132358                 0          2       0   

        height  pre_icu_los_days  readmission_status  weight  ...  \
117138   177.8          0.143056                   0   102.0  ...   
117139   185.4          0.188194                   0    83.9  ...   
117140   182.9          0.075000                   0   100.8  ...   

        h1_pao2fio2ratio_max  h1_pao2fio2ratio_min  aids  cirrhosis  \
117138                 163.0                 163.0     0          0   
117139                   NaN                   NaN     0          0   
117140                   NaN                   NaN     0          0   

        hepatic_failure  immunosuppression  leukemia  lymphoma  \
117138                0                  0         0         0   
117139                0                  0         0         0   
117140                0                  0         0         0   

        solid_tumor_with_metastasis  diabetes_mellitus  
117138                            0                  1  
117139                            0                  0  
117140                            0                  0  

[3 rows x 174 columns]

#### Weight, Height, BMI

##### weight

In [35]:
col = "weight"
df[col].unique()

array([ 73.9 ,  70.2 ,  95.3 , ..., 164.9 , 181.5 ,  64.65])

In [36]:
print(" NaN No: ",df[col].isna().sum())

 NaN No:  3106


In [37]:
df[col] = df[col].round(1)
df[col].unique()

array([ 73.9,  70.2,  95.3, ..., 178.4, 164.9, 181.5])

##### height

In [38]:
col = "height"
df[col].unique()

array([180.3 , 160.  , 172.7 , 165.1 , 188.  , 190.5 , 165.  , 170.2 ,
       175.3 , 154.9 , 193.  , 167.6 , 177.8 , 162.6 , 152.4 , 149.9 ,
       182.9 , 162.5 , 151.8 , 157.5 , 185.4 , 167.5 , 166.4 ,    nan,
       157.4 , 170.  , 183.  , 195.59, 161.3 , 182.8 , 154.3 , 175.2 ,
       167.  , 163.8 , 173.  , 171.5 , 179.1 , 151.1 , 187.9 , 142.2 ,
       189.2 , 168.9 , 149.  , 180.  , 152.  , 182.  , 175.  , 177.  ,
       176.5 , 167.7 , 144.8 , 149.8 , 147.3 , 137.2 , 156.2 , 174.  ,
       150.  , 158.  , 163.  , 154.2 , 179.  , 157.7 , 139.7 , 157.  ,
       178.  , 194.3 , 185.  , 153.7 , 155.  , 162.  , 172.5 , 184.2 ,
       161.9 , 181.6 , 162.4 , 158.8 , 154.6 , 180.2 , 170.3 , 169.  ,
       158.1 , 171.  , 173.4 , 187.3 , 181.4 , 177.9 , 147.  , 157.2 ,
       168.  , 152.6 , 148.4 , 184.5 , 164.  , 172.4 , 143.  , 172.  ,
       173.5 , 170.1 , 157.6 , 175.1 , 175.9 , 182.2 , 154.  , 182.6 ,
       160.1 , 148.6 , 162.3 , 164.5 , 176.8 , 177.2 , 186.7 , 168.7 ,
      

In [39]:
print(" NaN No: ",df[col].isna().sum())

 NaN No:  1854


In [40]:
df[col] = df[col].round(1)
df[col].unique()

array([180.3, 160. , 172.7, 165.1, 188. , 190.5, 165. , 170.2, 175.3,
       154.9, 193. , 167.6, 177.8, 162.6, 152.4, 149.9, 182.9, 162.5,
       151.8, 157.5, 185.4, 167.5, 166.4,   nan, 157.4, 170. , 183. ,
       195.6, 161.3, 182.8, 154.3, 175.2, 167. , 163.8, 173. , 171.5,
       179.1, 151.1, 187.9, 142.2, 189.2, 168.9, 149. , 180. , 152. ,
       182. , 175. , 177. , 176.5, 167.7, 144.8, 149.8, 147.3, 137.2,
       156.2, 174. , 150. , 158. , 163. , 154.2, 179. , 157.7, 139.7,
       157. , 178. , 194.3, 185. , 153.7, 155. , 162. , 172.5, 184.2,
       161.9, 181.6, 162.4, 158.8, 154.6, 180.2, 170.3, 169. , 158.1,
       171. , 173.4, 187.3, 181.4, 177.9, 147. , 157.2, 168. , 152.6,
       148.4, 184.5, 164. , 172.4, 143. , 172. , 173.5, 170.1, 157.6,
       175.1, 175.9, 182.2, 154. , 182.6, 160.1, 148.6, 162.3, 164.5,
       176.8, 177.2, 186.7, 168.7, 164.1, 160.2, 177.6, 191.8, 191. ,
       168.3, 160.3, 165.3, 177.7, 180.4, 182.7, 142. , 182.5, 166.3,
       184.4, 143.5,

##### BMI

In [41]:
df.drop(["height","weight"], inplace = True, axis=1)

In [42]:
col = "bmi"
df[col].unique()

array([22.73280282, 27.421875  , 31.95274882, ..., 42.27030676,
       17.57687531, 34.0223003 ])

In [43]:
print(" NaN No: ",df[col].isna().sum())

 NaN No:  4022


In [44]:
df[col] = df[col].round()
df[col].unique()

array([23., 27., 32., nan, 28., 57., 26., 38., 37., 36., 30., 24., 17.,
       22., 19., 35., 33., 15., 29., 21., 34., 20., 25., 46., 53., 31.,
       39., 16., 18., 48., 64., 40., 49., 42., 44., 41., 68., 45., 43.,
       56., 60., 50., 55., 61., 51., 47., 52., 58., 54., 59., 66., 65.,
       62., 63., 67.])

In [45]:
train_df_BMI =  {"Under": 0,"Normal": 1,"Over":2,"Obese":3,"Other/Unknown":4}

def bmiFloatToInt(value):
  try:
    if (value < 19):
      return 0
    elif (value >= 19 and value < 25):
      return 1
    elif (value >= 25 and value < 30):
      return 2
    elif (value >= 30):
      return 3 
  except:
    return 4

In [46]:
df[col] = df[col].apply(lambda row : bmiFloatToInt(row))
df[col] = df[col].fillna(4)

In [47]:
df[col].unique()

array([1., 2., 3., 4., 0.])

#### Simple KNN Method

In [88]:
def tryPlotKNN(column_name):
    sample_df = df.sample(frac=0.5,random_state=666)
    X = sample_df.drop([column_name], axis = 1).to_numpy()
    
    y = sample_df[column_name].to_numpy()
    
    X_train, X_test, y_train, y_test = train_test_split(X, y,stratify = y,test_size=0.25,random_state=0)

    print('Amostras de treino:')
    print(f' * X_train: {X_train.shape}')
    print(f' * y_train: {y_train.shape}')

    print('Amostras de teste:')
    print(f' * X_test: {X_test.shape}')
    print(f' * y_test: {y_test.shape}')

    #try:
    knn_model = KNeighborsClassifier(n_neighbors=5)
    knn_model.fit(X_train, y_train)
    print(f'Acurácia (Treino): {round(accuracy_score(y_train, knn_model.predict(X_train)), 2)}')
    print(f'Acurácia (Teste): {round(accuracy_score(y_test, knn_model.predict(X_test)), 2)}')
    #except ValueError:
    #    print("Strings are present or NaNs were found")


In [ ]:
to_drop = ["albumin_apache","bilirubin_apache","bun_apache","creatinine_apache","fio2_apache","gcs_eyes_apache","gcs_motor_apache","gcs_unable_apache",\
          "gcs_verbal_apache","glucose_apache",""]

In [91]:
## Fill albumin_apache, h1_pao2fio2ratio_max, h1_pao2fio2ratio_min

In [92]:
df.h1_pao2fio2ratio_max.fillna(int(df.h1_pao2fio2ratio_max.mean()), inplace=True)

In [63]:
tryPlotKNN("gender")

Amostras de treino:
 * X_train: (43906, 171)
 * y_train: (43906,)
Amostras de teste:
 * X_test: (14636, 171)
 * y_test: (14636,)


ValueError: Input contains NaN, infinity or a value too large for dtype('float64').